version: '2'
services:
  postgres:
    build: images/db
    environment:
     POSTGRES_PASSWORD: example
     POSTGRES_USER: example
  web:
    build: images/web
    # Map both HTTP and HTTPS
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - .:/app
    depends_on:
      - postgres
      - redis
    # Wait for the images to to boot and then run yarn
    command: ["./wait_for_it.sh", "postgres:5432", "--", "yarn"]
